apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bgd-v1
  template:
    metadata:
      labels:
        app: bgd-v1
    spec:
      containers:
      - name: bgd-v1
        image: quay.io/jwlim567/bgd/v1
        ports:
        - containerPort: 80
