apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green-deployment
  namespace: bgd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgd-v1
  strategy: {}
  template:
    metadata:
      labels:
        app: bgd-v1
    spec:
      containers:
      - image: quay.io/jwlim567/bgd/v1
        name: bgd-v1
        ports:
        - containerPort: 80
