apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  namespace: bgd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bgd-v1
      env: blue
  strategy: {}
  template:
    metadata:
      labels:
        app: bgd-v1
        env: blue
    spec:
      containers:
      - image: quay.io/jwlim567/bgd/v1
        name: bgd-v1
        ports:
        - containerPort: 8080
